---

#configuration des instances Backend
- name : Configuring back-end instances
  hosts: backends
  gather_facts: yes
  vars:
    test: "Mon user eductive25: le meilleur !"
  tasks:
#installation et configuration de nginx
    - name: Ensure Nginx package is installed
      apt:
        name: nginx
        state: latest
    - name: Configure kitten page
      template:
        src: templates/index.html.j2
        dest: /var/www/html/index.html
    - name: Configure Nginx to listen on the vRack
      template:
        src: templates/default.j2
        dest: /etc/nginx/sites-available/default
      notify:
        - Restart Nginx
#installation/configuration de docker et de ses dependances
    - name: Ensure Docker dependencies are installed
      apt:
        update_cache: true
        name:
          - apt-transport-https
          - ca-certificates
          - lsb-release
          - gnupg
        state: latest
    - name: Ensure key is succesfully installed
      apt_key:
        url: "https://download.docker.com/linux/debian/gpg"
    - name: Ensure repository is successfully updated
      apt_repository:
        repo: "deb https://download.docker.com/linux/debian bullseye stable"
    - name: Ensure successful installation of Docker
      apt:
        name:
          - docker
          - docker-compose
          - docker-compose-plugin
#installation du firewall
#    - name: Ensure firewall is installed
#      apt:
#        name: ufw
#        state: latest
#handlers des differentes composantes installees
  handlers:
    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
#    - name: Reload ufw (Firewall)
#      ansible.builtin.service:
#        name: ufw
#        state: reloaded

#configuration de l'instance Front-End
- name: Install and configure HaProxy on Front-End
  hosts: front
  tasks:
#installation et configuration de HaProxy
  - name: Ensure installation and update of HaProxy
    apt:
      name: haproxy
      state: latest
  - name: Ensure HaProxy has started
    service:
      name: haproxy
      state: started
  - name: Configurate HaProxy
    template:
      src: templates/haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
    notify:
    - Reload haproxy
#handlers des composantes installees
  handlers:
  - name: Reload haproxy
    ansible.builtin.service:
      name: haproxy
      state: reloaded
