---

#configuration du backend
- name : Configuring back-end instances
  hosts: backends
  gather_facts: yes
  vars:
    test: "Mon user eductive25: le meilleur !"
  tasks:
    - name: Ensure Nginx package is installed
      apt:
        name: nginx
        state: latest
    - name: Configure kitten page
      template:
        src: template/index.html.j2
        dest: /var/www/html/index/html
    - name: Configure Nginx to listen on the vRack
      template:
        src: template/default.j2
        dest: /etc/nginx/sites-available/default
      notify:
        - Restart nginx
  handlers:
    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted

#configuration de l'instance Front-End
- name: Install and configure HaProxy on Front-End
  hosts: front
  tasks:
  - name: Ensure installation and update of HaProxy
    apt:
      name: haproxy
      state: latest
  - name: Ensure HaProxy has started
    service:
      name: haproxy
      state: started
  - name: Configurate HaProxy
    template:
      src: templates/haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
    notify:
    - Reload haproxy
  handlers:
  - name: Reload haproxy
    ansible.builtin.service:
      name: haproxy
      state: reloaded
