---
- name: facts
  hosts: backends
  gather_facts: true

- name: Display facts
  hosts: localhost
  tasks:
#    - debug: var=inventory_hostname
#    - debug: var=ansible_hostname
    - debug: var=hostvars
